# `make init` will install the following packages

# Simple, fast and user-friendly alternative to find
brew "fd"

# Extremely fast Python package installer and resolver, written in Rust
brew "uv"

# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
