name: tests
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install zsh
        run: sudo apt-get --yes install zsh
        if: runner.os == 'Linux'
      - run: ./tests.sh
        shell: bash
